title: At Ease
description: A website for recording learning!
theme: just-the-docs

url: https://jpj-0510.github.io

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Set a path/url to a logo that will be displayed instead of the title



# Set a path/url to a favicon that will be displayed by the browser


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true


# Color scheme supports "light" (default) and "dark"


#supported by kramdown: block IALs.
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

# Set a path/url to a favicon that will be displayed by the browser
favicons:
  small: "/assets/favicon.png"
  large: "/assets/favicon.png"
